Download thread
VikSing88/SlackBot pull request #13
Opened 2021-07-23 09:04 UTC by HolySpiridon

2021-07-29 14:14 UTC, KorepanovAV requested changes
Возможно некоторые DTO классы будут больше не нужны. Их нужно в этом случае удалить.

2021-07-29 14:14 UTC, KorepanovAV commented on SlackBot/Program.cs
> +        .RegisterMessageShortcutHandler(shortcutCallbackID, new DownloadHandler(botToken, new LocalDownloader(pathToDownloadDirectory)));
```suggestion
        .RegisterMessageShortcutHandler(shortcutCallbackID, ctx =>
        {
          var slackApi = ctx.ServiceProvider.GetApiClient();
          return new DownloadHandler(slackApi, new LocalDownloader(botToken, slackApi, pathToDownloadDirectory));
        });
```

2021-07-29 14:14 UTC, KorepanovAV commented on SlackBot/Program.cs
> +    public static ThreadDTO GetThread(string messageTimestamp, string channel)
Переделать в метод расширения для `IConversationsApi` и вынести в отдельный класс. Параметры метода можно сохранить, вызывать в нем метод `IConversationsApi.Replies(...)`

2021-07-29 14:14 UTC, KorepanovAV commented on SlackBot/Program.cs
> +    public static void PostEphemeralMessageToUser(string message, string userId, string channelId)
Тоже переделать в метод расширения для `IChatApi`.

2021-07-29 14:14 UTC, KorepanovAV commented on SlackBot/Program.cs
> +    public static UserDTO GetUserNameById(string userId)
Тоже переделать в метод расширения для `IUsersApi`.

2021-08-02 11:11 UTC, R4ndyM4rsh commented on SlackBot/Program.cs
> +      slackService = new SlackServiceBuilder()
Заменил

2021-08-02 11:12 UTC, R4ndyM4rsh commented on SlackBot/DTOs/UserDTO.cs
> +    public string Name { get; set; }
Добавил свойство

2021-08-02 11:19 UTC, R4ndyM4rsh commented on SlackBot/DownloadFunctionality/DownloadHandler.cs
> +    public DownloadHandler(string botToken, IDownloader downloader)
Удалил все botToken и добавил аргумент ISlackApiClient slackApi

2021-08-02 11:20 UTC, R4ndyM4rsh commented on SlackBot/DownloadFunctionality/DownloadHandler.cs
> +          var pathToThread = downloader.DownloadThread(thread, request.Channel.Name, botToken);
Удалил botToken

2021-08-02 11:22 UTC, R4ndyM4rsh commented on SlackBot/DownloadFunctionality/IDownloader.cs
> +    string DownloadThread(ThreadDTO thread, string channelName, string botToken);
Удалил botToken

2021-08-02 11:24 UTC, R4ndyM4rsh commented on SlackBot/Program.cs
> +    private static SlackApiClient slackApi;
Изменил SlackApiClient на ISlackApiClient

2021-08-02 11:24 UTC, R4ndyM4rsh commented on SlackBot/Program.cs
> +        .RegisterMessageShortcutHandler(shortcutCallbackID, new DownloadHandler(botToken, new LocalDownloader(pathToDownloadDirectory)));
Заменил

2021-08-02 11:29 UTC, R4ndyM4rsh commented on SlackBot/Program.cs
> +    public static ThreadDTO GetThread(string messageTimestamp, string channel)
Выполнил

2021-08-02 11:29 UTC, R4ndyM4rsh commented on SlackBot/Program.cs
> +    public static void PostEphemeralMessageToUser(string message, string userId, string channelId)
Выполнил

2021-08-02 11:30 UTC, R4ndyM4rsh commented on SlackBot/Program.cs
> +    public static UserDTO GetUserNameById(string userId)
Выполнил

2021-08-02 13:04 UTC, KorepanovAV reviewed
Нужно починить сборку. Проверить в работе. Сейчас проект даже не собирается.

2021-08-06 06:19 UTC, KorepanovAV commented on SlackBot/DownloadFunctionality/LocalDownloader.cs
> +      var path = $@"{pathToThreadFolder}\files\{fileName}.{fileExtension}";
```cs
      var path = $@"{pathToThreadFolder}\files\{fileName}.{fileExtension}";
      while (System.IO.File.Exists(path))
      {
        if (int.TryParse(fileName[^2].ToString(), out int i))
          fileName = fileName.Remove(fileName.Length - 2, 2) + $"{i + 1})";
        else
          fileName += "(1)";
      }
```

Значение переменной `path` не обновляется, хотя `fileName` обновляется. Т.е. имя файла может в итоге быть не уникальным.
Нужно вернуть проверку значения `path` в цикл, например, как было:
```cs
while (System.IO.File.Exists($@"{pathToThreadFolder}\files\{fileName}.{fileExtension}"))
```

2021-08-06 06:21 UTC, KorepanovAV commented on SlackBot/Program.cs
> +    private static SlackApiClient slackApi;
Нужно повторить.

2021-08-06 06:29 UTC, KorepanovAV commented on SlackBot/DownloadFunctionality/LocalDownloader.cs
> +        var userName = slackApi.Users.GetUserNameById(message.User).User.Name;
```suggestion
        var userName = slackApi.Users.GetUserNameById(message.User).User.RealName;
```

2021-08-06 06:46 UTC, KorepanovAV commented on SlackBot/Program.cs
> +      };
```suggestion
    public static UserDTO GetUserNameById(this IUsersApi users, string userId)
    {
      var user = users.Info(userId).Result;
      DTOs.User DTOsUser = new DTOs.User
      {
        Name = user.Name,
        RealName = user.RealName
      };
```
Давай так. Чтобы не делать двойной вызов `Info(userId)`.

2021-08-06 07:31 UTC, KorepanovAV commented on SlackBot/DownloadFunctionality/LocalDownloader.cs
> +        foreach (var file in message.Files)
```suggestion
      {
        client.Proxy = new WebProxy { UseDefaultCredentials = true, };
        client.Headers.Add($"Authorization: Bearer {botToken}");
        foreach (var file in message.Files)
```

2021-08-06 07:32 UTC, KorepanovAV commented on SlackBot/DownloadFunctionality/LocalDownloader.cs
> +      var userName = slackApi.Users.GetUserNameById(firstMessageInThread.User).User.Name;
```suggestion
      var userName = slackApi.Users.GetUserNameById(firstMessageInThread.User).User.RealName;
```

2021-08-06 07:34 UTC, KorepanovAV commented
Смотреть закончил.
Есть немного мелких замечаний.
Остались старые ещё не исправленные.

2021-08-06 07:36 UTC, KorepanovAV reviewed
Теперь точно закончил смотреть.

2021-08-09 13:07 UTC, KorepanovAV requested changes
Ещё пара замечаний осталась.

2021-08-10 05:51 UTC, KorepanovAV approved these changes
Как оказалось два изменения я пропустил. Теперь всё ок.

2021-08-10 05:55 UTC, merged