Изменил логику общения с api slack`a на новую с использованием библио…
VikSing88/SlackBot pull request #14
Opened 2021-07-23 11:20 UTC by HolySpiridon

…теки SlackNet

2021-08-09 07:54 UTC, KorepanovAV commented on SlackBot/Program.cs
>          var oldMessageTSList = GetOldMessageList(list.items, channelInfo);
```suggestion
        var list = slackApi.Pins.List(channelInfo.ChannelID).Result.OfType<PinnedMessage>();
        var oldMessageTSList = GetOldMessageList(list, channelInfo);
```

2021-08-09 07:56 UTC, KorepanovAV requested changes
Посмотрел. Одно небольшое замечание.

2021-08-10 08:49 UTC, R4ndyM4rsh commented
> Посмотрел. Одно небольшое замечание.

Исправил

2021-08-10 08:53 UTC, KorepanovAV approved these changes

2021-08-10 09:28 UTC, merged