Добавил автопин новых сообщений
VikSing88/SlackBot pull request #18
Opened 2021-08-12 05:05 UTC by R4ndyM4rsh

2021-08-12 06:06 UTC, aledyad commented
Сейчас получается бот запинивает все новые сообщения во всех каналах, куда он добавлен.
Это неудобно.
Надо добавить в настройки каналов настройку, по которой эта функциональность будет включаться/выключаться. Назвать ее например AutoPinNewMessage = true|false, значение по умолчанию true.
Соответственно автопинить сообщения надо только в тех каналах, которые указаны в настройках бота, и в которых AutoPinNewMessage = true.

2021-08-12 06:07 UTC, aledyad commented
Еще не сделана вторая часть фичи:
>После запинивания писать в тред приветственное сообщение, которое должно быть можно задать в настройках для каждого наблюдаемого канала. Если приветственное сообщение не задано, то ничего в канал не писать.

2021-08-12 06:27 UTC, aledyad requested changes

2021-08-12 06:27 UTC, aledyad commented on SlackBot/MessageHandler.cs
> +  public class MessageHandler : IEventHandler<MessageEvent>
Классу надо дать имя, более точно описывающее его назначение. Предлагаю AutoPinMessageHandler.

2021-08-12 06:27 UTC, aledyad commented on SlackBot/MessageHandler.cs
> +    public Task Handle(MessageEvent slackEvent)
>slackEvent

переименовать в newMessageEvent

2021-08-12 06:27 UTC, aledyad commented on SlackBot/Program.cs
> +          var slackApi = slackService.GetApiClient();
Нехорошо здесь обращаться к slackService, т.к. это вызов метода, который возвращает значение для записи в эту переменную. Т.е. как будто идет обращение в будущее.

slackApi надо брать из переменной p, аналогично тому, как сделано в RegisterMessageShortcutHandler.

2021-08-12 06:27 UTC, aledyad commented on SlackBot/MessageHandler.cs
> +      Task.Run(() =>
Метод AddMessage возвращает значение типа Task, т.е. если делается запинивание, то в методе Handle можно возвращать сразу результат вызова AddMessage, а не оборачивать его в Task.Run.
Текущая реализация плоха еще тем, что код, вызвавший Handle, по факту не будет ожидать завершения вызова AddMessage, т.к. ему всегда возвращается "заглушка" Task.CompletedTask. Сейчас это не приведет к проблемам, т.к. приложение запущено всегда, но это не оправдывает такой код.

Как это должно выглядеть на мой взгляд:
```
      if (slackEvent.ThreadTs == null)
      { ...
        return slack.Pins.AddMessage(chanel, ts);
      }
      else
        return Task.CompletedTask;
```

2021-08-12 09:03 UTC, R4ndyM4rsh commented on SlackBot/MessageHandler.cs
> +  public class MessageHandler : IEventHandler<MessageEvent>
Переименовал класс MessageHandler в AutoPinMessageHandler

2021-08-12 09:04 UTC, R4ndyM4rsh commented on SlackBot/MessageHandler.cs
> +    public Task Handle(MessageEvent slackEvent)
Переименовал slackEvent в newMessageEvent

2021-08-12 09:06 UTC, R4ndyM4rsh commented on SlackBot/Program.cs
> +          var slackApi = slackService.GetApiClient();
Переделал. Теперь вызываю slackService через p

2021-08-12 09:06 UTC, R4ndyM4rsh commented on SlackBot/MessageHandler.cs
> +      Task.Run(() =>
Переделал

2021-08-13 06:45 UTC, aledyad requested changes

2021-08-13 06:45 UTC, aledyad commented on SlackBot/AutoPinMessageHandler.cs
> +          if ((chanel == chanelInfo.ChannelID) && (String.Compare(chanelInfo.AutoPinNewMessage, "true") == 0))
>String.Compare(chanelInfo.AutoPinNewMessage, "true") == 0)

такой код хрупкий.
по-хорошему надо еще на этапе чтения настроек парсить строку в bool (bool.Parse(...)), и дальше уже везде использовать булевское значение.

2021-08-13 06:45 UTC, aledyad commented on SlackBot/AutoPinMessageHandler.cs
> +            if (String.Compare(chanelInfo.WelcomeMessage, "") != 0)
```suggestion
            if (!string.IsNullOrEmpty(chanelInfo.WelcomeMessage))
```

2021-08-13 06:45 UTC, aledyad commented on SlackBot/Program.cs
> +          var autoPinNewMessage = config.GetSection($"Channels:{i}:AutoPinNewMessage").Value;
```suggestion
          var autoPinNewMessage = bool.Parse(config.GetSection($"Channels:{i}:AutoPinNewMessage").Value);
```

2021-08-13 06:45 UTC, aledyad commented on SlackBot/Program.cs
> +        var list2 = slackApi.Pins.List(channelInfo.ChannelID);
https://github.com/VikSing88/SlackBot/blob/06f9b818833567ecdea7478055e18411c7600b41/SlackBot/Program.cs#L272-L273
мусор?

2021-08-13 06:45 UTC, aledyad commented on SlackBot/SlackChannelInfo.cs
> +    public string AutoPinNewMessage { get; set; }
```suggestion
    public bool AutoPinNewMessage { get; set; }
```

2021-08-13 06:59 UTC, aledyad requested changes

2021-08-13 06:59 UTC, aledyad commented on README.md
> +Бот для Slack, который умеет отпинивать неактивные закрепленные сообщения спустя заданный промежуток дней, умеет пинить новые сообщения и приветсвовать пользователя, каналы для которых нужно пинить н
```suggestion
Бот для Slack, выполняющий вспомогательные функции в каналах консультирования отдела поддержки и разработки Directum 5.
Возможности:
- приветственное сообщение в треде для новых сообщений в канале;
- автоматическое закрепление (pin) новых сообщений в канале;
- уведомление об неактивных консультациях и их автоматическое открепление (unpin);
- скачивание треда с вложениями.
```

2021-08-13 06:59 UTC, aledyad commented on README.md
> +  - AutoPinMessage: разрешение для закрепления новых сообщений.
```suggestion
  - AutoPinMessage: автоматическое закрепление новых сообщений.
```

2021-08-13 06:59 UTC, aledyad commented on README.md
> +  - WelcomeMessage: приветсвенное сообщение.
```suggestion
  - WelcomeMessage: приветственное сообщение.
```

2021-08-13 07:20 UTC, R4ndyM4rsh commented on SlackBot/AutoPinMessageHandler.cs
> +          if ((chanel == chanelInfo.ChannelID) && (String.Compare(chanelInfo.AutoPinNewMessage, "true") == 0))
Исправил

2021-08-13 07:21 UTC, R4ndyM4rsh commented on SlackBot/AutoPinMessageHandler.cs
> +            if (String.Compare(chanelInfo.WelcomeMessage, "") != 0)
Исправил

2021-08-13 07:21 UTC, R4ndyM4rsh commented on SlackBot/Program.cs
> +          var autoPinNewMessage = config.GetSection($"Channels:{i}:AutoPinNewMessage").Value;
Исправил

2021-08-13 07:21 UTC, R4ndyM4rsh commented on SlackBot/Program.cs
> +        var list2 = slackApi.Pins.List(channelInfo.ChannelID);
Мусор убрал

2021-08-13 07:21 UTC, R4ndyM4rsh commented on SlackBot/SlackChannelInfo.cs
> +    public string AutoPinNewMessage { get; set; }
Исправил

2021-08-13 07:25 UTC, R4ndyM4rsh commented on README.md
> +Бот для Slack, который умеет отпинивать неактивные закрепленные сообщения спустя заданный промежуток дней, умеет пинить новые сообщения и приветсвовать пользователя, каналы для которых нужно пинить н
Изменил

2021-08-13 07:25 UTC, R4ndyM4rsh commented on README.md
> +  - AutoPinMessage: разрешение для закрепления новых сообщений.
Изменил

2021-08-13 07:25 UTC, R4ndyM4rsh commented on README.md
> +  - WelcomeMessage: приветсвенное сообщение.
Изменил

2021-08-13 07:52 UTC, aledyad approved these changes

2021-08-13 07:52 UTC, merged